********************* HealthCheck ******************
curl --location 'http://localhost:8000/api/healthcheck' \
--header 'channel: healthcheck' \
--header 'purpose: healthcheck' \
--header 'Content-Type: application/json' \
--data '{
    "service": "authentication"
}'
*****************************************************


********************* Login ************************
curl --location 'http://localhost:8080/api/authentication' \
--header 'purpose: login' \
--header 'channel: email' \
--header 'Content-Type: application/json' \
--header 'Cookie: token=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxZWY3NTczMi1jZmM4LTRmYWItYjgyOC1lZGMwYWM2YmU3OTMiLCJ1c2VybmFtZSI6ImFua2l0YW5hbmQyMTI1LXN0cnUtNTU1LTY5MWYiLCJlbWFpbCI6ImFua2l0YW5hbmQyMTI1QGdtYWlsLmNvbSIsInNvdXJjZSI6InNpZ251cFJlcXVlc3QiLCJpYXQiOjE3NDg0NjMxNjYsImV4cCI6MTc0ODU0OTU2Nn0.xAM-jGd3ULMNN03YAsO_EP5oOAZ30S6HqRvXxbAhsdBDIqBSCzHuKc1ZSS1BCrDgqNTFdUTfD-TcwDJTvZAgNw' \
--data-raw '{
    "email": "ankitanand2125@gmail.com",
    "password": "P@ssw0rd123!"
}'
*****************************************************


********************* Register **********************
curl --location 'http://localhost:8080/api/authentication' \
--header 'purpose: register' \
--header 'channel: email' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Ankit Anand",
    "email": "ankitanand2125@gmail.com",
    "password": "P@ssw0rd123!",
    "primaryCountryCode": "US",
    "phoneNumber": "+1-555-123-4567",
    "alternatePhone": "",
    "secondaryCountryCode": ""
}'
***************************************************


**************** Passwordless **********************
curl --location 'http://localhost:8080/api/authentication' \
--header 'purpose: magiclink' \
--header 'channel: passwordless' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "ankitanand2125@gmail.com"
}'
***************************************************

***************************************************
curl --location 'http://localhost:8080/api/authentication' \
--header 'purpose: forgotPassword' \
--header 'channel: email' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "ankitanand2125@gmail.com"
}'
***************************************************
